// Code generated by "stringer --type=BookingStatus"; DO NOT EDIT.

package booking

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Reserved-0]
	_ = x[Booked-1]
}

const _BookingStatus_name = "ReservedBooked"

var _BookingStatus_index = [...]uint8{0, 8, 14}

func (i BookingStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BookingStatus_index)-1 {
		return "BookingStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BookingStatus_name[_BookingStatus_index[idx]:_BookingStatus_index[idx+1]]
}
