// Code generated by "stringer -type=TicketState"; DO NOT EDIT.

package ticket

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[booked-0]
	_ = x[available-1]
}

const _TicketState_name = "bookedavailable"

var _TicketState_index = [...]uint8{0, 6, 15}

func (i TicketState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TicketState_index)-1 {
		return "TicketState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TicketState_name[_TicketState_index[idx]:_TicketState_index[idx+1]]
}
