basePath: /v1
definitions:
  errors.Error:
    properties:
      error:
        type: string
    type: object
  event.EventDTO:
    properties:
      category:
        type: string
      id:
        type: string
      name:
        type: string
      start_time:
        type: string
      tickets:
        items:
          $ref: '#/definitions/ticket.TicketDTO'
        type: array
      total_available_tickets:
        type: string
      venue:
        type: string
    type: object
  ticket.TicketDTO:
    properties:
      id:
        type: integer
      seat:
        type: string
    type: object
host: localhost:8081
info:
  contact:
    email: safder.h@outlook.com
    name: Ahmed Hasnat Safder
  description: This is a sample RESTful API with limited features of ticket master
  title: APP API
  version: "1.0"
paths:
  /../healthcheck:
    get:
      description: Read health
      responses:
        "200":
          description: OK
      summary: Read health
      tags:
      - health
  /events:
    get:
      consumes:
      - application/json
      description: List events
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/event.EventDTO'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      summary: List events
      tags:
      - events
  /events/{id}:
    get:
      consumes:
      - application/json
      description: Read event
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/event.EventDTO'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      summary: Read event
      tags:
      - events
swagger: "2.0"
